name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Cache Gradle dependencies to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 4. Grant execution permission for gradlew
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 5. Lint Check
      - name: Run Lint (App module)
        run: ./gradlew :app:lint

      # 6. Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebug

      # 7. Build APK
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      # 8. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: weather-now-later-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Setup local.properties with API_KEY
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties